### ISSUE TITLE
Where is the HTML page? I can only see comments

### ISSUE THREAD

**Issue by stbensonimoh** [praisejahuzoma/javascript-fundamental-project#1]
https://github.com/praisejahuzoma/javascript-fundamental-project/blob/4bf75cf9a7f32fb25980230986540b3ee69b7759/Question-2/index.html#L2

I was expecting to see a HTML document like so:
```html
<!DOCTYPE html>
<html>
<head>
<title>Question 2</title>
</head>

<script>
// and your alert() code and answer will go inside here.
</script>
</html>
```

**Comment by stbensonimoh** [comment]
@osumgbachiamaka please take a look. Maybe I am not getting something right here.

**Comment by osumgbachiamaka** [comment]
@stbensonimoh this is question number what?

Can the questions be added in a readMe file to help understand what's happening in the repo?

**Comment by stbensonimoh** [comment]
This is question number 2. The links is [HERE](https://github.com/stbensonimoh/intern-practice-assignment/blob/main/questions/javascript-fundamentals.md#question-2-the-script-tag)

**Comment by osumgbachiamaka** [comment]
okay, this is so cool
![amazing](https://media.giphy.com/media/xUA7b2iWIZd3e2jyec/giphy.gif)
